# -*- coding: utf-8 -*-
"""Guild Roster Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_mAXP1M78iOBBLxJ56K0AiqKt2hdeBZ
"""

# นำเข้าไลบรารีที่จำเป็น
import discord
from discord import app_commands
from discord.ui import Button, Modal, TextInput, View
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import os
import asyncio
import nest_asyncio

# Apply nest_asyncio to allow nested event loops
nest_asyncio.apply()





# Commented out IPython magic to ensure Python compatibility.
# %pip install -q nest_asyncio



















# =================================================================
# Cell 2: การตั้งค่าตัวแปรและการเชื่อมต่อ Google Sheets
# =================================================================

# 📌 ข้อมูล Discord ของคุณ:
# **โปรดแทนที่ "YOUR_BOT_TOKEN" ด้วยโทเค็นบอทจริงของคุณ**
# **วิธีรับโทเค็น:** ไปที่ Discord Developer Portal -> Applications -> เลือกบอทของคุณ -> Bot -> Token -> Copy
BOT_TOKEN = " "
# Server ID (Guild ID):
# **โปรดแทนที่ "YOUR_GUILD_ID" ด้วย ID เซิร์ฟเวอร์ Discord ของคุณ**
# **วิธีรับ Guild ID:** เปิดใช้งาน Developer Mode ใน Discord (User Settings -> Advanced) -> คลิกขวาที่ไอคอนเซิร์ฟเวอร์ -> Copy ID
GUILD_ID = 1422980759433777194 # Example: 123456789012345678
# ID ของ Google Sheet ที่คุณสร้างไว้ (ดึงมาจาก URL ของชีต):
# **โปรดแทนที่ 'YOUR_SHEET_ID' ด้วย ID ของ Google Sheet ของคุณ**
# **วิธีรับ Sheet ID:** เปิด Google Sheet ของคุณ -> ID คือส่วนที่อยู่ระหว่าง "/d/" และ "/edit" ใน URL
SHEET_ID = '1G64zZTLEeS9cvu5pwIT3g7kxuq_4P5LK13qajQ01YZU'
# ชื่อ WorkSheet ใน Google Sheet (โดยปกติคือ 'Sheet1' หรือชื่อที่คุณตั้ง)
# **โปรดแทนที่ 'YOUR_WORKSHEET_NAME' ด้วยชื่อ Worksheet ของคุณ**
WORKSHEET_NAME = 'ชีต1'


# โหลดข้อมูล Service Account จากไฟล์ JSON
# **โปรดแก้ไขพาธนี้ให้ชี้ไปยังไฟล์ service_account.json ของคุณบน Google Drive หรืออัปโหลดใน Colab**
SERVICE_ACCOUNT_FILE = 'service_account.json'
service_account_info = None
try:
    with open(SERVICE_ACCOUNT_FILE, 'r') as f:
        service_account_info = json.load(f)
    print(f"✅ พบและโหลดไฟล์ Service Account '{SERVICE_ACCOUNT_FILE}' สำเร็จ")
except FileNotFoundError:
    print(f"❌ ไม่พบไฟล์ {SERVICE_ACCOUNT_FILE} กรุณาตรวจสอบว่าอยู่ในโฟลเดอร์เดียวกัน หรือพาธถูกต้อง")
    service_account_info = None # Ensure service_account_info is None on error
except Exception as e:
    print(f"❌ เกิดข้อผิดพลาดในการโหลดไฟล์ Service Account: {e}")
    service_account_info = None


# เชื่อมต่อ Google Sheets (จะทำต่อเมื่อโหลด service_account_info สำเร็จ)
client_gspread = None
sheet = None
if service_account_info:
    try:
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds = ServiceAccountCredentials.from_json_keyfile_dict(service_account_info, scope)
        client_gspread = gspread.authorize(creds)
        print("✅ เชื่อมต่อ Gspread Client สำเร็จ")
        try:
            # เปิด Google Sheet ด้วย ID
            spreadsheet = client_gspread.open_by_key(SHEET_ID)
            print(f"✅ พบ Google Sheet ด้วย ID '{SHEET_ID}' แล้ว")

            # พยายามเปิด Worksheet ที่ระบุ
            try:
                sheet = spreadsheet.worksheet(WORKSHEET_NAME)
                print(f"✅ เชื่อมต่อ Worksheet '{WORKSHEET_NAME}' สำเร็จแล้ว")
            except gspread.WorksheetNotFound:
                print(f"❌ ไม่พบ WorkSheet ชื่อ '{WORKSHEET_NAME}' ใน Google Sheet ID '{SHEET_ID}'")
                print("--- รายชื่อ Worksheets ที่พบใน Google Sheet นี้ ---")
                try:
                    worksheets = spreadsheet.worksheets()
                    for ws in worksheets:
                        print(f"- {ws.title}")
                    print("---------------------------------------------")
                    print(f"โปรดตรวจสอบชื่อ Worksheet ด้านบน และแก้ไขตัวแปร WORKSHEET_NAME ในโค้ดให้ตรงกัน")
                except Exception as list_e:
                    print(f"เกิดข้อผิดพลาดในการดึงรายชื่อ Worksheets: {list_e}")
                sheet = None # Ensure sheet is None on error
            except Exception as e:
                print(f"❌ เกิดข้อผิดพลาดในการเปิด Worksheet: {e}")
                sheet = None # Ensure sheet is None on error

        except gspread.SpreadsheetNotFound:
             print(f"❌ ไม่พบ Google Sheet ด้วย ID '{SHEET_ID}'")
             print("โปรดตรวจสอบ ID ของ Google Sheet ใน URL และยืนยันว่าได้ให้สิทธิ์ 'Editor' แก่ Service Account Email แล้ว")
             client_gspread = None
             sheet = None # Ensure sheet is None on error
        except Exception as e:
            print(f"❌ เกิดข้อผิดพลาดในการเชื่อมต่อ Google Sheet: {e}")
            print("โปรดตรวจสอบสิทธิ์การแชร์ Google Sheet กับ Service Account ของคุณ")
            client_gspread = None
            sheet = None # Ensure sheet is None on error
    except Exception as e:
        print(f"❌ เกิดข้อผิดพลาดในการเชื่อมต่อ Google Sheets API: {e}")
        print("โปรดตรวจสอบสิทธิ์การแชร์ Google Sheet กับ Service Account ของคุณ")
        client_gspread = None
        sheet = None # Ensure sheet is None on error
else:
    print("⚠️ ไม่สามารถเชื่อมต่อ Google Sheets ได้เนื่องจากไม่สามารถโหลดไฟล์ Service Account ได้")

# ตรวจสอบว่า sheet ถูกเชื่อมต่อสำเร็จหรือไม่ ก่อนที่จะดำเนินการในเซลล์ถัดไป
if sheet is None:
    print("⚠️ ไม่สามารถดำเนินการในขั้นตอนที่ต้องใช้ Google Sheets ได้")











"""# Task
Organize the provided Python code for a Discord bot that interacts with Google Sheets into logical cells in a Colab notebook, ensuring necessary libraries are installed, variables are set up, Google Sheets is connected, UI components (Modal, View) are defined, bot commands are set up, and the bot can be run, and then inform the user that the cells have been organized and are ready for testing.

## ติดตั้งไลบรารี

### Subtask:
ติดตั้งไลบรารีที่จำเป็น (`discord.py`, `gspread`, `oauth2client`, `nest_asyncio`) สำหรับการทำงานของบอทและการเชื่อมต่อ Google Sheets.

**Reasoning**:
Install the required libraries using pip.
"""

# Commented out IPython magic to ensure Python compatibility.
# ติดตั้งไลบรารีที่จำเป็น
# %pip install -q discord.py gspread oauth2client nest_asyncio

"""## ตั้งค่าตัวแปรและเชื่อมต่อ google sheets

### Subtask:
กำหนดค่า `BOT_TOKEN`, `GUILD_ID`, `SHEET_ID`, `WORKSHEET_NAME`, และ `SERVICE_ACCOUNT_FILE` จากนั้นโหลดไฟล์ Service Account JSON และทำการเชื่อมต่อกับ Google Sheets.

**Reasoning**:
Define the necessary variables, load the service account file, and establish the connection to Google Sheets as requested by the subtask instructions. This block combines steps 1 through 5 of the instructions.
"""

# =================================================================
# การตั้งค่าตัวแปรและการเชื่อมต่อ Google Sheets
# =================================================================

# 📌 ข้อมูล Discord ของคุณ:
# **โปรดแทนที่ "YOUR_BOT_TOKEN" ด้วยโทเค็นบอทจริงของคุณ**
# **วิธีรับโทเค็น:** ไปที่ Discord Developer Portal -> Applications -> เลือกบอทของคุณ -> Bot -> Token -> Copy
BOT_TOKEN = " " # Replaced placeholder with provided token
# Server ID (Guild ID):
# **โปรดแทนที่ "YOUR_GUILD_ID" ด้วย ID เซิร์ฟเวอร์ Discord ของคุณ**
# **วิธีรับ Guild ID:** เปิดใช้งาน Developer Mode ใน Discord (User Settings -> Advanced) -> คลิกขวาที่ไอคอนเซิร์ฟเวอร์ -> Copy ID
GUILD_ID = 1422980759433777194 # Replaced placeholder with provided GUILD_ID
# ID ของ Google Sheet ที่คุณสร้างไว้ (ดึงมาจาก URL ของชีต):
# **โปรดแทนที่ 'YOUR_SHEET_ID' ด้วย ID ของ Google Sheet ของคุณ**
# **วิธีรับ Sheet ID:** เปิด Google Sheet ของคุณ -> ID คือส่วนที่อยู่ระหว่าง "/d/" และ "/edit" ใน URL
SHEET_ID = '1G64zZTLEeS9cvu5pwIT3g7kxuq_4P5LK13qajQ01YZU' # Replaced placeholder with provided SHEET_ID
# ชื่อ WorkSheet ใน Google Sheet (โดยปกติคือ 'Sheet1' หรือชื่อที่คุณตั้ง)
# **โปรดแทนที่ 'YOUR_WORKSHEET_NAME' ด้วยชื่อ Worksheet ของคุณ**
WORKSHEET_NAME = 'ชีต1' # Replaced placeholder with provided WORKSHEET_NAME


# โหลดข้อมูล Service Account จากไฟล์ JSON
# **โปรดแก้ไขพาธนี้ให้ชี้ไปยังไฟล์ service_account.json ของคุณบน Google Drive หรืออัปโหลดใน Colab**
SERVICE_ACCOUNT_FILE = 'service_account.json'
service_account_info = None
try:
    with open(SERVICE_ACCOUNT_FILE, 'r') as f:
        service_account_info = json.load(f)
    print(f"✅ พบและโหลดไฟล์ Service Account '{SERVICE_ACCOUNT_FILE}' สำเร็จ")
except FileNotFoundError:
    print(f"❌ ไม่พบไฟล์ {SERVICE_ACCOUNT_FILE} กรุณาตรวจสอบว่าอยู่ในโฟลเดอร์เดียวกัน หรือพาธถูกต้อง")
    service_account_info = None # Ensure service_account_info is None on error
except Exception as e:
    print(f"❌ เกิดข้อผิดพลาดในการโหลดไฟล์ Service Account: {e}")
    service_account_info = None


# เชื่อมต่อ Google Sheets (จะทำต่อเมื่อโหลด service_account_info สำเร็จ)
client_gspread = None
sheet = None
if service_account_info:
    try:
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds = ServiceAccountCredentials.from_json_keyfile_dict(service_account_info, scope)
        client_gspread = gspread.authorize(creds)
        print("✅ เชื่อมต่อ Gspread Client สำเร็จ")
        try:
            # เปิด Google Sheet ด้วย ID
            spreadsheet = client_gspread.open_by_key(SHEET_ID)
            print(f"✅ พบ Google Sheet ด้วย ID '{SHEET_ID}' แล้ว")

            # พยายามเปิด Worksheet ที่ระบุ
            try:
                sheet = spreadsheet.worksheet(WORKSHEET_NAME)
                print(f"✅ เชื่อมต่อ Worksheet '{WORKSHEET_NAME}' สำเร็จแล้ว")
            except gspread.WorksheetNotFound:
                print(f"❌ ไม่พบ WorkSheet ชื่อ '{WORKSHEET_NAME}' ใน Google Sheet ID '{SHEET_ID}'")
                print("--- รายชื่อ Worksheets ที่พบใน Google Sheet นี้ ---")
                try:
                    worksheets = spreadsheet.worksheets()
                    for ws in worksheets:
                        print(f"- {ws.title}")
                    print("---------------------------------------------")
                    print(f"โปรดตรวจสอบชื่อ Worksheet ด้านบน และแก้ไขตัวแปร WORKSHEET_NAME ในโค้ดให้ตรงกัน")
                except Exception as list_e:
                    print(f"เกิดข้อผิดพลาดในการดึงรายชื่อ Worksheets: {list_e}")
                sheet = None # Ensure sheet is None on error
            except Exception as e:
                print(f"❌ เกิดข้อผิดพลาดในการเปิด Worksheet: {e}")
                sheet = None # Ensure sheet is None on error

        except gspread.SpreadsheetNotFound:
             print(f"❌ ไม่พบ Google Sheet ด้วย ID '{SHEET_ID}'")
             print("โปรดตรวจสอบ ID ของ Google Sheet ใน URL และยืนยันว่าได้ให้สิทธิ์ 'Editor' แก่ Service Account Email แล้ว")
             client_gspread = None
             sheet = None # Ensure sheet is None on error
        except Exception as e:
            print(f"❌ เกิดข้อผิดพลาดในการเชื่อมต่อ Google Sheet: {e}")
            print("โปรดตรวจสอบสิทธิ์การแชร์ Google Sheet กับ Service Account ของคุณ")
            client_gspread = None
            sheet = None # Ensure sheet is None on error
    except Exception as e:
        print(f"❌ เกิดข้อผิดพลาดในการเชื่อมต่อ Google Sheets API: {e}")
        print("โปรดตรวจสอบสิทธิ์การแชร์ Google Sheet กับ Service Account ของคุณ")
        client_gspread = None
        sheet = None # Ensure sheet is None on error
else:
    print("⚠️ ไม่สามารถเชื่อมต่อ Google Sheets ได้เนื่องจากไม่สามารถโหลดไฟล์ Service Account ได้")

# ตรวจสอบว่า sheet ถูกเชื่อมต่อสำเร็จหรือไม่ ก่อนที่จะดำเนินการในเซลล์ถัดไป
if sheet is None:
    print("⚠️ ไม่สามารถดำเนินการในขั้นตอนที่ต้องใช้ Google Sheets ได้")

"""# Task
Add the provided Discord bot code to the notebook.

## Define ui components (modal, view)

### Subtask:
Define the necessary classes for Discord UI elements like Modals and Views to handle user interactions.

**Reasoning**:
Define the Discord UI elements (Modal and View) as requested by the subtask instructions.
"""

# =================================================================
# เซลล์ 4: การสร้าง UI Component (Modal, View)
# =================================================================

# Modal สำหรับรับข้อมูลผู้เล่นใหม่
class AddPlayerModal(Modal, title='เพิ่มข้อมูลผู้เล่นใหม่'):
    name = TextInput(label='ชื่อในเกม (In-game Name)', placeholder='ป้อนชื่อตัวละครในเกม...', max_length=50)
    discord_id = TextInput(label='Discord ID', placeholder='ป้อน Discord ID (ตัวอย่าง: your_name#1234)', max_length=50, required=False)
    role = TextInput(label='บทบาท (เช่น Tank, Healer, DPS)', placeholder='ป้อนบทบาทหลักของคุณ...', max_length=50)
    level = TextInput(label='ระดับ (Level)', placeholder='ป้อนระดับตัวละครของคุณ...', max_length=10)
    notes = TextInput(label='หมายเหตุ (ถ้ามี)', placeholder='ข้อมูลเพิ่มเติมเกี่ยวกับผู้เล่น...', style=discord.TextStyle.long, required=False)

    async def on_submit(self, interaction: discord.Interaction):
        # ตรวจสอบการเชื่อมต่อ Google Sheets อีกครั้งก่อนบันทึกข้อมูล
        if sheet is None:
            await interaction.response.send_message('❌ ไม่สามารถบันทึกข้อมูลได้: ไม่สามารถเชื่อมต่อ Google Sheets ได้', ephemeral=True)
            return

        try:
            # ดึงข้อมูลจาก Modal
            player_data = [
                str(interaction.user.id), # Discord User ID ของผู้ที่กรอก Modal
                self.name.value,
                self.discord_id.value if self.discord_id.value else str(interaction.user), # ใช้ Username หากไม่มี ID
                self.role.value,
                self.level.value,
                self.notes.value if self.notes.value else '', # ใช้ค่าว่างถ้าไม่มีหมายเหตุ
                str(datetime.datetime.now()) # เวลาที่เพิ่มข้อมูล
            ]

            # เพิ่มข้อมูลลงใน Google Sheet
            sheet.append_row(player_data)

            await interaction.response.send_message(f'✅ เพิ่มข้อมูลผู้เล่น **{self.name.value}** เรียบร้อยแล้ว!', ephemeral=True)

        except Exception as e:
            print(f"❌ เกิดข้อผิดพลาดในการบันทึกข้อมูลลง Google Sheet: {e}")
            await interaction.response.send_message('❌ เกิดข้อผิดพลาดในการบันทึกข้อมูล กรุณาลองใหม่อีกครั้ง', ephemeral=True)

# View สำหรับแสดงปุ่ม
class PlayerView(View):
    def __init__(self, *, timeout=180):
        super().__init__(timeout=timeout)

    @discord.ui.button(label="เพิ่มผู้เล่นใหม่", style=discord.ButtonStyle.primary)
    async def add_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # สร้าง Modal และแสดงให้ผู้ใช้กรอกข้อมูล
        modal = AddPlayerModal()
        await interaction.response.send_modal(modal)

    @discord.ui.button(label="ดูรายชื่อผู้เล่น", style=discord.ButtonStyle.secondary)
    async def view_players_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป เพื่อดึงและแสดงข้อมูลจาก Google Sheets
        await interaction.response.send_message("ฟังก์ชันดูรายชื่อผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

    @discord.ui.button(label="อัปเดตข้อมูล", style=discord.ButtonStyle.success)
    async def update_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
         # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป สำหรับการอัปเดตข้อมูล
         await interaction.response.send_message("ฟังก์ชันอัปเดตข้อมูลผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

    @discord.ui.button(label="ลบผู้เล่น", style=discord.ButtonStyle.danger)
    async def delete_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป สำหรับการลบข้อมูล
        await interaction.response.send_message("ฟังก์ชันลบผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

"""## Set up discord bot and commands

### Subtask:
Initialize the Discord client, define the command tree, and create the Discord bot commands (e.g., `/สมัคร`).

**Reasoning**:
Initialize the Discord client, define the command tree, and create the asynchronous function for the `/สมัคร` command, including the decorator and the response with the view.
"""

# =================================================================
# เซลล์ 5: การตั้งค่า Client, Command Tree และคำสั่ง Discord
# =================================================================

# กำหนด Intent ที่บอทต้องการ
# ต้องเปิดใช้งาน Intents ที่จำเป็นใน Discord Developer Portal -> Applications -> บอทของคุณ -> Bot -> Privileged Gateway Intents
intents = discord.Intents.default()
intents.message_content = True # สำหรับการอ่านข้อความ (หากจำเป็น)
intents.members = True         # สำหรับการเข้าถึงข้อมูลสมาชิก (จำเป็นสำหรับ Guild ID)
intents.guilds = True          # สำหรับการเข้าถึงข้อมูลเซิร์ฟเวอร์ (จำเป็นสำหรับ Guild ID)

# สร้าง Instance ของ Client
client = discord.Client(intents=intents)

# สร้าง Instance ของ Command Tree
tree = app_commands.CommandTree(client)

# กำหนด Guild (Server) ที่ต้องการใช้งานคำสั่ง Slash Command
# การกำหนด Guild เฉพาะจะทำให้คำสั่ง Slash Command พร้อมใช้งานทันทีใน Guild นั้นๆ
# หากไม่กำหนด Guild คำสั่งจะถูก Sync เป็น Global Command ซึ่งอาจใช้เวลาถึง 1 ชั่วโมง
my_guild = discord.Object(id=GUILD_ID) # แทนที่ด้วย ID เซิร์ฟเวอร์ของคุณ

# =================================================================
# สร้างคำสั่ง Slash Command: /สมัคร
# =================================================================

@tree.command(guild=my_guild, name='สมัคร', description='ลงทะเบียนเป็นผู้เล่นใหม่ในกิลด์')
async def register_command(interaction: discord.Interaction):
    """สร้างปุ่มสำหรับให้ผู้ใช้ลงทะเบียน"""
    # สร้าง View ที่มีปุ่ม "เพิ่มผู้เล่นใหม่"
    view = PlayerView()

    # ส่งข้อความพร้อม View ไปยังผู้ใช้
    await interaction.response.send_message(
        "คลิกปุ่มด้านล่างเพื่อลงทะเบียนเป็นผู้เล่นใหม่:",
        view=view,
        ephemeral=True # ทำให้ข้อความนี้เห็นเฉพาะผู้ใช้ที่พิมพ์คำสั่ง
    )

# =================================================================
# Event: เมื่อบอทพร้อมใช้งาน
# =================================================================

@client.event
async def on_ready():
    # Sync คำสั่ง Slash Command กับ Discord
    # หากมีการแก้ไขคำสั่ง ควร Un-comment บรรทัดนี้เพื่อ Sync คำสั่งอีกครั้ง
    # การ Sync ใน Guild เฉพาะจะเร็วกว่าการ Sync แบบ Global มาก
    await tree.sync(guild=my_guild)
    print(f'✅ บอท {client.user} พร้อมใช้งานแล้ว')
    print(f'✅ คำสั่ง Slash Commands ได้ถูก Sync กับ Guild ID: {GUILD_ID} แล้ว')
    print('---')

# =================================================================
# Event: เมื่อมีข้อความถูกส่งเข้ามา (ตัวอย่าง)
# =================================================================
# @client.event
# async def on_message(message):
#     # ไม่ต้องประมวลผลข้อความที่บอทส่งเอง
#     if message.author == client.user:
#         return

#     # ตัวอย่าง: ตอบกลับข้อความ 'hello'
#     if message.content.lower() == 'hello':
#         await message.channel.send('Hello!')

#     # หากต้องการให้บอทประมวลผลคำสั่งแบบ Prefix commands ด้วย
#     # ต้องเพิ่มโค้ดที่นี่และใช้ discord.ext.commands.Bot
#     # เช่น await client.process_commands(message)


# =================================================================
# เซลล์ 6: การรันบอท
# =================================================================
# จะอยู่ในเซลล์ถัดไปเพื่อความสะดวกในการควบคุมการรัน/หยุดบอท

"""## Implement google sheets interaction logic

### Subtask:
Add the necessary code to the `on_submit` method of the `AddPlayerModal` to interact with the Google Sheet by appending the collected data. This requires adding the `datetime` import.

**Reasoning**:
Add the necessary code to the `on_submit` method of the `AddPlayerModal` to interact with the Google Sheet by appending the collected data. This requires adding the `datetime` import.
"""

# =================================================================
# เซลล์ 4: การสร้าง UI Component (Modal, View)
# =================================================================

import datetime # Import datetime for timestamp

# Modal สำหรับรับข้อมูลผู้เล่นใหม่
class AddPlayerModal(Modal, title='เพิ่มข้อมูลผู้เล่นใหม่'):
    name = TextInput(label='ชื่อในเกม (In-game Name)', placeholder='ป้อนชื่อตัวละครในเกม...', max_length=50)
    discord_id = TextInput(label='Discord ID', placeholder='ป้อน Discord ID (ตัวอย่าง: your_name#1234)', max_length=50, required=False)
    role = TextInput(label='บทบาท (เช่น Tank, Healer, DPS)', placeholder='ป้อนบทบาทหลักของคุณ...', max_length=50)
    level = TextInput(label='ระดับ (Level)', placeholder='ป้อนระดับตัวละครของคุณ...', max_length=10)
    notes = TextInput(label='หมายเหตุ (ถ้ามี)', placeholder='ข้อมูลเพิ่มเติมเกี่ยวกับผู้เล่น...', style=discord.TextStyle.long, required=False)

    async def on_submit(self, interaction: discord.Interaction):
        # ตรวจสอบการเชื่อมต่อ Google Sheets อีกครั้งก่อนบันทึกข้อมูล
        if sheet is None:
            await interaction.response.send_message('❌ ไม่สามารถบันทึกข้อมูลได้: ไม่สามารถเชื่อมต่อ Google Sheets ได้', ephemeral=True)
            return

        try:
            # ดึงข้อมูลจาก Modal
            player_data = [
                str(interaction.user.id), # Discord User ID ของผู้ที่กรอก Modal
                self.name.value,
                self.discord_id.value if self.discord_id.value else str(interaction.user), # ใช้ Username หากไม่มี ID
                self.role.value,
                self.level.value,
                self.notes.value if self.notes.value else '', # ใช้ค่าว่างถ้าไม่มีหมายเหตุ
                str(datetime.datetime.now()) # เวลาที่เพิ่มข้อมูล
            ]

            # เพิ่มข้อมูลลงใน Google Sheet
            sheet.append_row(player_data)

            await interaction.response.send_message(f'✅ เพิ่มข้อมูลผู้เล่น **{self.name.value}** เรียบร้อยแล้ว!', ephemeral=True)

        except Exception as e:
            print(f"❌ เกิดข้อผิดพลาดในการบันทึกข้อมูลลง Google Sheet: {e}")
            await interaction.response.send_message('❌ เกิดข้อผิดพลาดในการบันทึกข้อมูล กรุณาลองใหม่อีกครั้ง', ephemeral=True)

# View สำหรับแสดงปุ่ม
class PlayerView(View):
    def __init__(self, *, timeout=180):
        super().__init__(timeout=timeout)

    @discord.ui.button(label="เพิ่มผู้เล่นใหม่", style=discord.ButtonStyle.primary)
    async def add_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # สร้าง Modal และแสดงให้ผู้ใช้กรอกข้อมูล
        modal = AddPlayerModal()
        await interaction.response.send_modal(modal)

    @discord.ui.button(label="ดูรายชื่อผู้เล่น", style=discord.ButtonStyle.secondary)
    async def view_players_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป เพื่อดึงและแสดงข้อมูลจาก Google Sheets
        await interaction.response.send_message("ฟังก์ชันดูรายชื่อผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

    @discord.ui.button(label="อัปเดตข้อมูล", style=discord.ButtonStyle.success)
    async def update_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
         # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป สำหรับการอัปเดตข้อมูล
         await interaction.response.send_message("ฟังก์ชันอัปเดตข้อมูลผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

    @discord.ui.button(label="ลบผู้เล่น", style=discord.ButtonStyle.danger)
    async def delete_player_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # ฟังก์ชันนี้จะถูกเติมเต็มในขั้นตอนต่อไป สำหรับการลบข้อมูล
        await interaction.response.send_message("ฟังก์ชันลบผู้เล่นจะถูกเพิ่มในภายหลัง!", ephemeral=True)

"""## Add event handlers

### Subtask:
Include event handlers like `on_ready` to confirm when the bot is online and ready.

**Reasoning**:
Define the on_ready event handler to synchronize slash commands as per the instructions.
"""

# =================================================================
# เซลล์ 5: การตั้งค่า Client, Command Tree และคำสั่ง Discord
# =================================================================

# กำหนด Intent ที่บอทต้องการ
# ต้องเปิดใช้งาน Intents ที่จำเป็นใน Discord Developer Portal -> Applications -> บอทของคุณ -> Bot -> Privileged Gateway Intents
intents = discord.Intents.default()
intents.message_content = True # สำหรับการอ่านข้อความ (หากจำเป็น)
intents.members = True         # สำหรับการเข้าถึงข้อมูลสมาชิก (จำเป็นสำหรับ Guild ID)
intents.guilds = True          # สำหรับการเข้าถึงข้อมูลเซิร์ฟเวอร์ (จำเป็นสำหรับ Guild ID)

# สร้าง Instance ของ Client
client = discord.Client(intents=intents)

# สร้าง Instance ของ Command Tree
tree = app_commands.CommandTree(client)

# กำหนด Guild (Server) ที่ต้องการใช้งานคำสั่ง Slash Command
# การกำหนด Guild เฉพาะจะทำให้คำสั่ง Slash Command พร้อมใช้งานทันทีใน Guild นั้นๆ
# หากไม่กำหนด Guild คำสั่งจะถูก Sync เป็น Global Command ซึ่งอาจใช้เวลาถึง 1 ชั่วโมง
my_guild = discord.Object(id=GUILD_ID) # แทนที่ด้วย ID เซิร์ฟเวอร์ของคุณ

# =================================================================
# สร้างคำสั่ง Slash Command: /สมัคร
# =================================================================

@tree.command(guild=my_guild, name='สมัคร', description='ลงทะเบียนเป็นผู้เล่นใหม่ในกิลด์')
async def register_command(interaction: discord.Interaction):
    """สร้างปุ่มสำหรับให้ผู้ใช้ลงทะเบียน"""
    # สร้าง View ที่มีปุ่ม "เพิ่มผู้เล่นใหม่"
    view = PlayerView()

    # ส่งข้อความพร้อม View ไปยังผู้ใช้
    await interaction.response.send_message(
        "คลิกปุ่มด้านล่างเพื่อลงทะเบียนเป็นผู้เล่นใหม่:",
        view=view,
        ephemeral=True # ทำให้ข้อความนี้เห็นเฉพาะผู้ใช้ที่พิมพ์คำสั่ง
    )

# =================================================================
# Event: เมื่อบอทพร้อมใช้งาน
# =================================================================

@client.event
async def on_ready():
    # Sync คำสั่ง Slash Command กับ Discord
    # หากมีการแก้ไขคำสั่ง ควร Un-comment บรรทัดนี้เพื่อ Sync คำสั่งอีกครั้ง
    # การ Sync ใน Guild เฉพาะจะเร็วกว่าการ Sync แบบ Global มาก
    await tree.sync(guild=my_guild)
    print(f'✅ บอท {client.user} พร้อมใช้งานแล้ว')
    print(f'✅ คำสั่ง Slash Commands ได้ถูก Sync กับ Guild ID: {GUILD_ID} แล้ว')
    print('---')

# =================================================================
# Event: เมื่อมีข้อความถูกส่งเข้ามา (ตัวอย่าง)
# =================================================================
# @client.event
# async def on_message(message):
#     # ไม่ต้องประมวลผลข้อความที่บอทส่งเอง
#     if message.author == client.user:
#         return

#     # ตัวอย่าง: ตอบกลับข้อความ 'hello'
#     if message.content.lower() == 'hello':
#         await message.channel.send('Hello!')

#     # หากต้องการให้บอทประมวลผลคำสั่งแบบ Prefix commands ด้วย
#     # ต้องเพิ่มโค้ดที่นี่และใช้ discord.ext.commands.Bot
#     # เช่น await client.process_commands(message)


# =================================================================
# เซลล์ 6: การรันบอท
# =================================================================
# จะอยู่ในเซลล์ถัดไปเพื่อความสะดวกในการควบคุมการรัน/หยุดบอท

"""## Run the discord bot

### Subtask:
Add the code to run the Discord bot using the provided token.

**Reasoning**:
Add the code to run the Discord bot using the provided token.
"""

# =================================================================
# เซลล์ 6: การรันบอท
# =================================================================
# รันบอทด้วยโทเค็นของคุณ
# บรรทัดนี้ควรเป็นบรรทัดสุดท้ายในเซลล์นี้ และควรอยู่ในเซลล์แยกต่างหากเพื่อให้สามารถหยุดการทำงานของบอทได้ง่าย
print("กำลังเริ่มบอท...")
try:
    client.run(BOT_TOKEN)
except Exception as e:
    print(f"❌ เกิดข้อผิดพลาดในการรันบอท: {e}")
    print("โปรดตรวจสอบ BOT_TOKEN และการเชื่อมต่ออินเทอร์เน็ตของคุณ")